### ISSUE TITLE
"Makes the HUD Go Nuts"

### ISSUE THREAD

**Issue by ghost** [TheIcyStar/Numerical-Health-Values#1]
This is what Doctor Twilight said in the comments of the GameBanana submission. I will be looking into this

**Comment by TheIcyStar** [comment]
I don't know what was wrong, I tested out the files I have and they were fine. Not sure what the issue was for him.

**Comment by TheIcyStar** [comment]
Apparently the guy was *using a 2007 client of tf2*, most likely a troll.

**Comment by ghost** [comment]
HA
