### ISSUE TITLE
Minmode support

### ISSUE THREAD

**Issue by TheIcyStar** [TheIcyStar/Numerical-Health-Values#3]
The numbers are there, but don't display properly.
Example: https://i.imgur.com/pmelUaW.jpg

**Comment by zJoacks** [comment]
Hey icy, i fixed minmode but im not really sure how to use github, so ill leave the images here and see what you think
![20210703234208_1](https://user-images.githubusercontent.com/82543066/124372507-4eab1600-dc58-11eb-911a-e48095482a35.jpg)
![20210703234205_1](https://user-images.githubusercontent.com/82543066/124372510-5c609b80-dc58-11eb-8748-93b3a23f8435.jpg)

**Comment by TheIcyStar** [comment]
Hey that's awesome! I appreciate you doing this

I can help out with making a proper pull request for you. Please attach your changed files here and I'll handle the rest

**Comment by zJoacks** [comment]
[numericalhealthvalues_fixed.zip](https://github.com/TheIcyStar/Numerical-Health-Values/files/6766196/numericalhealthvalues_fixed.zip)
here it is, im glad i could help

**Comment by TheIcyStar** [comment]
Minmode now added as of 6a1bd821024f73956ae5a17c56e7f4b2014bbd1f!
